### PR TITLE
Disable assert removal and add flag for property renaming

### PR DESCRIPTION
**Pull request by lomegor**

### CODE REVIEW

**Comment by jjpersch** [comment]
Please create a branch and merge the work there.

This should not be merged to the master branch, as the master branch tracks the upstream master.

**Comment by lomegor** [comment]
Is there any reason for that? As far as I can see, this repository was only created for delivery engineering. We are phasing out the use of custom modifications to closure compiler, and this repository doesn't have any regular updates. This is only a place where we can keep the updates to the compiler.

**Comment by jjpersch** [comment]
We push upstream updates to master as the upstream changes.

The suggestion is:

Create a branch specifically for monetate changes to some newer version of the closure-compiler, just like the `r1791.monetate` branches does for holding our changes to that version, then we tag specific monetate releases like `r1791.monetate6`.  We are able to easily see our changes to that version, such as https://github.com/monetate/closure-compiler/compare/r1791...monetate:r1791.monetate.

**Comment by jjpersch** [comment]
I would also recommends making clearly marking monetate specific flags as `--monetate-...` so we know they are not standard closure compiler options.

**Comment by lomegor** [comment]
Yeah, I get what that workflow used to be. But as I said, I thought this repo was only used by Delivery Engineering, and we are trying to phase it out. As you can see, there's been a total of two PRs to this repository since its existence, we don't modify it that much. So the question is what's the value of keeping separate branches when we can still update the master branch to upstream anyways.

On the monetate flags, yes, that's how it used to be. But again, the question is why that would be necessary and how it would help. We already know we are using a custom version of closure compiler, and some of the things (like the not removal of the mc.assert) are not governed by flags, so only some things would be clear that are Monetate only.

The questions are basically:
1. Is anyone else aside from DE using this project?
2. Is there an advantage to using a separate branch when this codebase is updated less than once per year?
3. What advantage do we get by marking flags as monetate only when some parts of the compiler will still not be clearly marked as such?

**Comment by jjpersch** [comment]
It is simply our existing convention all our repositories of vendored code.
The repository tracks the upstream, and our changes are on separate branches.

Our changes:
- exist on a branch, so we can easily see our changes from the upstream branch point
- are tagged with a release tag so the builds are reproducible

We keep the upstream branches pristine so that tracking is automated.

**Pull request merged**
